# Site settings
title: Angular - Das umfassende Handbuch
header-img: img/bg-home.jpg
email: mail@angular-buch.de
copyright_name: Christoph Höller
description: "Die Homepage zum JavaScript Fachbuch 'Angular das umfassende Handbuch' aus dem Rheinwerk-Verlag. Jetzt bestellen. Kickstart, Komponenten-Konzepte, Formulare, Routing, RxJS, TypeScript, Performance-Optimierung. Mit Angular 13 Support"
baseurl: ""
url: "http://angular-buch.de"
twitter_username: chris_hoeller
github_username: choeller
email_username: christoph.hoeller@googlemail.com
collections:
  - chapter
  - testimonials

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
exclude: [ "less","node_modules","Gruntfile.js","package.json","README.md" ]

gems: [ jekyll-paginate, jekyll-feed ]
